// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
#include <cstdint>
#include <span>
namespace xaos {
// XaoS classic default palette, generated by the same 31 control colours and
// 8-entry linear segments as src/util/palette.cpp in the original XaoS.
std::span<const uint32_t> classicDefaultPalette() noexcept;
uint32_t classicIterationColor(uint32_t iteration) noexcept;
}
