// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
#include <cstdint>
#include <span>

namespace xaos {

enum class InColoring:uint8_t {
    Black=0,ZMag,Decomposition,RealImag,Difference,CosMag,
    MagCosReal2,SinReal2Imag2,AtanProduct,Squares
};
enum class OutColoring:uint8_t {
    Iter=0,IterReal,IterImag,IterRealImag,IterAll,
    BinaryDecomposition,Biomorphs,Potential,ColorDecomposition,Smooth
};

const char* inColoringName(InColoring) noexcept;
const char* outColoringName(OutColoring) noexcept;

// XaoS classic default palette, generated by the same 31 control colours and
// 8-entry linear segments as src/util/palette.cpp in the original XaoS.
/// Returns the lazily generated classic XaoS default palette.
std::span<const uint32_t> classicDefaultPalette() noexcept;

/// Maps an 8.8 fixed-point palette coordinate through the classic palette.
/// Entry zero remains reserved for black/interior; shift is in whole palette entries.
uint32_t classicPaletteColorFixed(int64_t fixed8,int shift=0) noexcept;

/// Maps an escape iteration to the classic XaoS palette entry.
uint32_t classicIterationColor(uint32_t iteration,int shift=0) noexcept;

}
